name: Publish Python Package to PyPI

# Trigger the workflow when a tag matching v*.*.* (e.g., v0.1.0) is pushed
# Versioning is manual: Update version in pyproject.toml (or elsewhere),
# commit, then create and push a matching tag (e.g., git tag v0.1.1 && git push origin v0.1.1)
on:
  push:
    tags:
      - 'v*.*.*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish-to-pypi:
    name: Build and publish Python distribution to PyPI
    runs-on: ubuntu-latest

    # Specify the environment configured in PyPI and GitHub repository settings
    environment: pypi_awali_db_mapping

    # Grant permissions for the workflow to request an OpenID Connect token
    permissions:
      id-token: write # Required for OIDC authentication with PyPI
      contents: read  # Required to checkout the code

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install build dependencies
      run: pip install build

    - name: Build package
      run: python -m build

    - name: Publish package distributions to PyPI
      # Use the official PyPA action to handle OIDC authentication automatically
      uses: pypa/gh-action-pypi-publish@release/v1
      # No 'user' or 'password' needed here, OIDC is handled via permissions
